// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWebApi.Infrastructure.Persistence;

#nullable disable

namespace VehicleWebApi.Infrastructure.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260310175352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.BodyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BodyType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coupé"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Convertible"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Station Wagon"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Minivan"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sports Car"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pickup Truck"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Electric Vehicle"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Semi-Truck"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dump Truck"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Box Truck"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Flatbed Truck"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Refrigerated Truck"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Tanker Truck"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Tow Truck"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Concrete Mixer Truck"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Garbage Truck"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Fire Truck"
                        });
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer", (string)null);
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId", "Name")
                        .IsUnique();

                    b.ToTable("Model", (string)null);
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.ModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "Year")
                        .IsUnique();

                    b.ToTable("ModelVersion", (string)null);
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelVersionId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicle", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Truck"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Motorcycle"
                        });
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Car", b =>
                {
                    b.HasBaseType("VehicleWebApi.Domain.Entities.Vehicle");

                    b.Property<int?>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DoorsQuantity")
                        .HasColumnType("int");

                    b.Property<bool?>("HasSunroof")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TrunkLiters")
                        .HasColumnType("decimal(10,2)");

                    b.HasIndex("BodyTypeId");

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Motorcycle", b =>
                {
                    b.HasBaseType("VehicleWebApi.Domain.Entities.Vehicle");

                    b.Property<int>("EngineDisplacement")
                        .HasColumnType("int");

                    b.Property<string>("HandlebarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("HasElectricStart")
                        .HasColumnType("bit");

                    b.ToTable("Motorcycle", (string)null);
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Truck", b =>
                {
                    b.HasBaseType("VehicleWebApi.Domain.Entities.Vehicle");

                    b.Property<int?>("AxlesQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("LoadCapacityInTons")
                        .HasColumnType("decimal(10,2)");

                    b.HasIndex("BodyTypeId");

                    b.ToTable("Truck", (string)null);
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Model", b =>
                {
                    b.HasOne("VehicleWebApi.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.ModelVersion", b =>
                {
                    b.HasOne("VehicleWebApi.Domain.Entities.Model", "Model")
                        .WithMany("Versions")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("VehicleWebApi.Domain.Entities.ModelVersion", "ModelVersion")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleWebApi.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelVersion");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Car", b =>
                {
                    b.HasOne("VehicleWebApi.Domain.Entities.BodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VehicleWebApi.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("VehicleWebApi.Domain.Entities.Car", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Motorcycle", b =>
                {
                    b.HasOne("VehicleWebApi.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("VehicleWebApi.Domain.Entities.Motorcycle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Truck", b =>
                {
                    b.HasOne("VehicleWebApi.Domain.Entities.BodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleWebApi.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("VehicleWebApi.Domain.Entities.Truck", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.Model", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("VehicleWebApi.Domain.Entities.ModelVersion", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
